name: 🐛 Bug Report
description: Report a reproducible bug to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please fill out **all sections** to help us quickly identify and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly describe the issue.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Windows 11, macOS Sonoma, Ubuntu 22.04

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste logs or attach screenshots if available.